// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orbis.Infrastructure.Persistence;

#nullable disable

namespace Orbis.Infrastructure.Persistence.DirectoryMigrations
{
    [DbContext(typeof(DirectoryDbContext))]
    [Migration("20260917162648_InitialDirectory")]
    partial class InitialDirectory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("directory")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orbis.Domain.Identity.ExternalIdentity", b =>
                {
                    b.Property<string>("Issuer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer")
                        .UseCollation("C");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject")
                        .UseCollation("C");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Issuer", "Subject");

                    b.HasIndex("UserId");

                    b.ToTable("external_identities", "directory");
                });

            modelBuilder.Entity("Orbis.Domain.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.ToTable("users", "directory", t =>
                        {
                            t.HasCheckConstraint("ck_user_id", "id <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("Orbis.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tenants", "directory", t =>
                        {
                            t.HasCheckConstraint("ck_tenant_id", "id <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("Orbis.Domain.Tenancy.TenantDomain", b =>
                {
                    b.Property<string>("Host")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("host")
                        .UseCollation("C");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Host");

                    b.HasIndex("TenantId");

                    b.ToTable("tenant_domains", "directory");
                });

            modelBuilder.Entity("Orbis.Domain.Identity.ExternalIdentity", b =>
                {
                    b.HasOne("Orbis.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbis.Domain.Tenancy.TenantDomain", b =>
                {
                    b.HasOne("Orbis.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
