// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orbis.Infrastructure.Persistence;

#nullable disable

namespace Orbis.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260923165133_ReadMemberPermission")]
    partial class ReadMemberPermission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orbis.Domain.Identity.Membership", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer")
                        .HasColumnName("permissions");

                    b.HasKey("TenantId", "UserId");

                    b.ToTable("memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_membership_ids", "tenant_id <> '00000000-0000-0000-0000-000000000000' AND user_id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_membership_permissions", "permissions BETWEEN 0 AND 255");
                        });
                });

            modelBuilder.Entity("Orbis.Domain.WorkOrders.WorkOrder", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("ProviderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "CustomerUserId");

                    b.HasIndex("TenantId", "ProviderUserId");

                    b.HasIndex("TenantId", "CreatedAt", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("work_orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_description", "length(btrim(description)) > 0");

                            t.HasCheckConstraint("ck_order_provider", "status NOT IN (1, 2, 3, 4) OR provider_user_id IS NOT NULL");

                            t.HasCheckConstraint("ck_order_status", "status BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_order_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Orbis.Domain.WorkOrders.WorkOrderAudit", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<long>("OrderVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("order_version");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "ActorId");

                    b.HasIndex("TenantId", "OrderId");

                    b.ToTable("work_order_audit", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_audit_action", "action IN ('work-order.requested','work-order.assigned','work-order.accepted','work-order.started','work-order.completed','work-order.cancelled')");

                            t.HasCheckConstraint("ck_order_audit_version", "order_version > 0");
                        });
                });

            modelBuilder.Entity("Orbis.Infrastructure.Persistence.OrderCreationReceipt", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint")
                        .UseCollation("C");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.HasKey("TenantId", "ActorId", "Key")
                        .HasName("pk_order_creation_receipts");

                    b.HasIndex("TenantId", "OrderId");

                    b.ToTable("order_creation_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_creation_fingerprint", "fingerprint ~ '^[0-9A-F]{64}$'");

                            t.HasCheckConstraint("ck_creation_key", "key <> '00000000-0000-0000-0000-000000000000'");
                        });
                });

            modelBuilder.Entity("Orbis.Infrastructure.Persistence.OrderTransitionReceipt", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint")
                        .UseCollation("C");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TenantId", "ActorId", "Action", "Key")
                        .HasName("pk_order_transition_receipts");

                    b.HasIndex("TenantId", "OrderId");

                    b.ToTable("order_transition_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_transition_action", "action BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_transition_fingerprint", "fingerprint ~ '^[0-9A-F]{64}$'");

                            t.HasCheckConstraint("ck_transition_key", "key <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_transition_result", "status BETWEEN 1 AND 5 AND version > 1");
                        });
                });

            modelBuilder.Entity("Orbis.Domain.WorkOrders.WorkOrder", b =>
                {
                    b.HasOne("Orbis.Domain.Identity.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CustomerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbis.Domain.Identity.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProviderUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Orbis.Domain.WorkOrders.WorkOrderAudit", b =>
                {
                    b.HasOne("Orbis.Domain.Identity.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbis.Domain.WorkOrders.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbis.Infrastructure.Persistence.OrderCreationReceipt", b =>
                {
                    b.HasOne("Orbis.Domain.Identity.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbis.Domain.WorkOrders.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbis.Infrastructure.Persistence.OrderTransitionReceipt", b =>
                {
                    b.HasOne("Orbis.Domain.Identity.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbis.Domain.WorkOrders.WorkOrder", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
