// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orbis.Infrastructure.Persistence;

#nullable disable

namespace Orbis.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260917162654_LinkDirectory")]
    partial class LinkDirectory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orbis.Domain.Identity.Membership", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer")
                        .HasColumnName("permissions");

                    b.HasKey("TenantId", "UserId");

                    b.ToTable("memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_membership_ids", "tenant_id <> '00000000-0000-0000-0000-000000000000' AND user_id <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("ck_membership_permissions", "permissions BETWEEN 0 AND 127");
                        });
                });

            modelBuilder.Entity("Orbis.Domain.WorkOrders.WorkOrder", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("ProviderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "CustomerUserId");

                    b.HasIndex("TenantId", "ProviderUserId");

                    b.HasIndex("TenantId", "CreatedAt", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("work_orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_description", "length(btrim(description)) > 0");

                            t.HasCheckConstraint("ck_order_provider", "status NOT IN (1, 2, 3, 4) OR provider_user_id IS NOT NULL");

                            t.HasCheckConstraint("ck_order_status", "status BETWEEN 0 AND 5");

                            t.HasCheckConstraint("ck_order_version", "version > 0");
                        });
                });

            modelBuilder.Entity("Orbis.Domain.WorkOrders.WorkOrder", b =>
                {
                    b.HasOne("Orbis.Domain.Identity.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CustomerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbis.Domain.Identity.Membership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ProviderUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
